// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"github.com/kainonly/collector/v3/app"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*app.App, error) {
	values, err := LoadStaticValues()
	if err != nil {
		return nil, err
	}
	conn, err := UseNats(values)
	if err != nil {
		return nil, err
	}
	jetStream, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	keyValue, err := UseKeyValue(values, jetStream)
	if err != nil {
		return nil, err
	}
	client, err := UseMongo(values)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(values, client)
	scheduler, err := UseSchedule()
	if err != nil {
		return nil, err
	}
	inject := NewInject(values, conn, jetStream, keyValue, client, database, scheduler)
	appApp := app.Initialize(inject)
	return appApp, nil
}
