// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/weplanx/collector/v3/app"
	"github.com/weplanx/collector/v3/common"
)

// Injectors from wire.go:

func NewApp() (*app.App, error) {
	values, err := LoadStaticValues()
	if err != nil {
		return nil, err
	}
	client, err := UseMongo(values)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(values, client)
	conn, err := UseNats(values)
	if err != nil {
		return nil, err
	}
	jetStreamContext, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	keyValue, err := UseKeyValue(values, jetStreamContext)
	if err != nil {
		return nil, err
	}
	inject := &common.Inject{
		V:  values,
		Mc: client,
		Db: database,
		Js: jetStreamContext,
		Kv: keyValue,
	}
	appApp := app.Initialize(inject)
	return appApp, nil
}
