// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/weplanx/collector/v3/app"
	"github.com/weplanx/collector/v3/common"
)

// Injectors from wire.go:

func NewApp() (*app.App, error) {
	values, err := LoadStaticValues()
	if err != nil {
		return nil, err
	}
	conn, err := UseNats(values)
	if err != nil {
		return nil, err
	}
	jetStream, err := UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	keyValue, err := UseKeyValue(values, jetStream)
	if err != nil {
		return nil, err
	}
	client, err := UseMongo(values)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(values, client)
	scheduler, err := UseSchedule()
	if err != nil {
		return nil, err
	}
	inject := &common.Inject{
		V:        values,
		Nc:       conn,
		Js:       jetStream,
		Kv:       keyValue,
		Mc:       client,
		Db:       database,
		Schedule: scheduler,
	}
	appApp := app.Initialize(inject)
	return appApp, nil
}
