mode: debug
namespace: alpha
description: 轻量队列流收集器
nats:
  hosts:
    - nats://127.0.0.1:1222
    - nats://127.0.0.1:1223
    - nats://127.0.0.1:1224
  token: s3cr3t
database:
  url: mongodb://localhost:27017
  name: example
